
[ClassVersion("0.1.0.0"), FriendlyName("xDhcpServerOption119Value")]
class DSC_DhcpServerOption119ValueResource : OMI_BaseResource
{
    [Write, Description("Specifies whether DHCP option 119 is configured at the server level."), ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] String Ensure;
    [Write, Description("Array of search domains.")] String SearchDomains[];
};
